### PR TITLE
Fix logic for showing hold notes in timeline

### LINKED ISSUE #231: HoldNote doesn't show up in notes timeline if it starts before visible timeline and ends after visible timeline

### PR DESCRIPTION
**Pull request by maxrchung**
Closes #231 

tiny changes xD

### CODE REVIEW

**Comment by maxrchung** [comment]
Test comment for github bot

**Comment by maxrchung** [comment]
Another comment for github bot

**Comment by maxrchung** [comment]
test cement

**Comment by maxrchung** [comment]
If you can see this message, it means that I have correctly configured the GitHub Discord bot to post generic comments made in a pull request. This was done by checking the Issue comments box in the webhook configuration. As far as comments are concerned, there's also a Commit comments box that I can also check. Do we want to enable this? As far as I'm concerned, we will pretty much never comment directly on commits, so I don't really want this. At this point, I think it's best to go the most restrictive route and only add specific webhook features as we see fit.

image

**Review by Xenocidel — APPROVED** [review]

**Review by Naranja-Sagged — APPROVED** [review]

**Pull request merged**
