### PR TITLE
Implement color input in command panel

### LINKED ISSUE #448: Implement color input in command panel
As a developer, I want to implement the color input into the command panel so that we can use the color input to easily select colors.

### PR DESCRIPTION
**Pull request by maxrchung**
Closes #448

### CODE REVIEW

**Comment by Xenocidel** [comment]
The first time you click to open the ColorPicker it always defaults to (0,0,0) rather than applying the color that was already in the field.

**Comment by maxrchung** [comment]
> The first time you click to open the ColorPicker it always defaults to (0,0,0) rather than applying the color that was already in the field. Subsequent clicks to open do not revert back to black.
> EDIT: Looks like if you copy another command up and open the ColorPicker it jumps to a different color altogether.

Should be fixed with https://github.com/maxrchung/S2VX/pull/461/commits/12b9d6db63144ae36ec571fee4d8f8d9fff8214d. The code comments mention a possible recursion issue, but I did not encounter it.

**Comment by Naranja-Sagged** [comment]
I think only 1 color picker should be able to be open at the same time since having 2 open looks kinda jank. The color picker on the right always overlaps the one on the left so I don't think it's too useful

**Comment by maxrchung** [comment]
> I think only 1 color picker should be able to be open at the same time since having 2 open looks kinda jank. The color picker on the right always overlaps the one on the left so I don't think it's too useful

I considered this, but after prototyping and testing a bit, I think it was kind of hard to hook up the value inputs to a single color picker. So, at least coding design-wise, I think this is easier to reason with. As for the overlap issues, I can rearrange the inputs and adjust the input sizing.

image

**Comment by Xenocidel** [comment]
When editing a command, the color picker is under the other commands
image

**Comment by maxrchung** [comment]
> When editing a command, the color picker is under the other commands
> image

Fixed in https://github.com/maxrchung/S2VX/pull/461/commits/1501c22ab4b36cb2624ecd924c50b727cbb24719

**Review by Xenocidel — APPROVED** [review]

**Review by Naranja-Sagged — APPROVED** [review]

**Pull request merged**
